"""Add media_urls to content

Revision ID: 6ee29206939c
Revises: 4e8fafc1319f
Create Date: 2025-05-11 04:46:50.149019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee29206939c'
down_revision = '4e8fafc1319f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_urls', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('media_urls')

    # ### end Alembic commands ###
